#! /usr/bin/env python2.7
from pylab import *

data = genfromtxt('armada_atm_NH3_2.7_H2O_2.7.txt', skip_header = 2)
temp = data[::-2,2]
cp   = data[::-2,-3]
ntemp = len(temp)

with open('jupiter_real_gas_cp.cpp', 'w') as file:
  file.write("// Table of realistic cp of Jupiter's atmosphere\n")
  file.write("// Generated by Cheng Li (cli@gps.caltech.edu) for Juno MWR using Armada-3.0 model output\n")
  file.write("// Includes temperature dependent cp from H2, He and CH4\n")
  file.write("// Shomate equations are used for T > 300, assuming normal H2.\n")
  file.write("// Rotational lines are used for T < 300.\n")
  file.write("// Data file if mwr_PJ01_p01.8_2.7x2.7.atm\n")
  file.write("// California Institute of Technology\n")
  file.write("// Aug 11, 2019\n")
  file.write("\n")

  file.write('#include "../athena.hpp"\n')
  file.write('#include "../math_funcs.hpp"\n')
  file.write("\n")

  file.write("Real cp[%d] = {    // J/(mol K)\n" % ntemp)
  for i in range(ntemp - 1):
    file.write("  %.2f," % cp[i])
    if (i+1) % 10 == 0:
      file.write("\n")
  file.write("  %.2f};\n" % cp[-1])
  file.write("\n")

  file.write("Real temp[%d] = {  // K;\n" % len(temp))
  for i in range(ntemp - 1):
    file.write("  %.2f," % temp[i])
    if (i+1) % 10 == 0:
      file.write("\n")
  file.write("  %.2f};\n" % temp[-1])
  file.write("\n")

  file.write("Real const Rgas = 8.314462;\n")
  file.write("\n")

  file.write("void update_gamma(Real& gamma, Real rcp[], Real const prim[]) {\n")
  file.write("  Real cp_real = _interp1(prim[IDN], cp, temp, %d);\n" % ntemp)
  file.write("  gamma = cp_real/(cp_real - Rgas);\n")
  file.write("}\n")
